# docker-compose.yml
version: '3.7'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - pdf-service 

  pdf-service:
    build: ./pdf-service
    ports:
      - "5001:5001"
